<?php

namespace GS\RedirectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends EntityRepository
{
}
